### TEST FOR CINECA'S GITLAB CI PIPELINE TO SUBMIT A JOB TO THE GALILEO CLUSTER USING SLURM
stages:
  - test_cluster_submission

submit_test_job:
  stage: test_cluster_submission
  # This uses GitLab's internal tracking variable to find the local registry safely
  image: $CI_REGISTRY/hpc/hpc-service:latest
  tags:
    - x86_64
    - cpu
    - docker
  script:
    - echo "Testing pipeline via local registry variable..."
    - hpc-service submit --script submit_job.sh