### TEST FOR CINECA'S GITLAB CI PIPELINE TO SUBMIT A JOB TO THE GALILEO CLUSTER USING SLURM
stages:
  - test_cluster_submission

submit_test_job:
  stage: test_cluster_submission
  # This pattern instructs the local runner daemon to grab the image out of 
  # its own cluster proxy registry, completely satisfying the "always" pull policy.
  image: gitlab.hpc.cineca.it:5050/hpc/hpc-service:latest
  tags:
    - x86_64
    - cpu
    - docker
  script:
    - echo "Testing official internal port pipeline path..."
    - hpc-service submit --script submit_job.sh