# .github/workflows/automated-CD.yml
name: Build and publish Apptainer image

on:
  push:
    branches: [dev]

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Apptainer image
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.4

      - name: Build .sif
        run: sudo apptainer build singularity/astralog.sif singularity/Singularity.def # build without fakeroot but sudo
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2 # use the Releases github action
        with:
          tag_name: latest-sif
          files: singularity/astralog.sif
          token: ${{ secrets.GITHUB_TOKEN }} # github configures it by itself
